//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AISDoeduSam.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string mainImg { get; set; }
        public string Manufacture { get; set; }
        public Nullable<byte> C_isActive { get; set; }
        public Nullable<decimal> Price { get; set; }
    }
}
